apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: argocd
spec:
  project: default
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  source:
    helm:
      valueFiles:
      - values-staging.yaml 
    path: project/helm
    repoURL: https://github.com/mhazrd/techtrends
    targetRevision: HEAD
